<a href="https://colab.research.google.com/github/mashrur-rahman-fahim/Machine_learning_projects/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Create a random tensor with shape (7, 7).

In [3]:
import torch
rand_tensor=torch.rand(7,7)
rand_tensor

tensor([[0.5153, 0.3227, 0.1825, 0.2982, 0.2684, 0.8212, 0.6890],
        [0.6962, 0.7199, 0.1393, 0.1114, 0.7791, 0.0179, 0.7062],
        [0.3587, 0.7271, 0.6907, 0.8979, 0.7952, 0.6222, 0.8494],
        [0.8605, 0.0149, 0.7345, 0.1251, 0.0534, 0.4844, 0.1153],
        [0.5597, 0.2895, 0.4170, 0.9894, 0.1936, 0.6065, 0.9296],
        [0.2448, 0.8305, 0.2518, 0.5508, 0.4183, 0.7857, 0.1152],
        [0.3558, 0.7354, 0.4552, 0.2866, 0.7170, 0.3467, 0.4497]])

##Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [17]:
import torch
rand_tensor1=torch.rand(1,7)
reshape_tensor1=torch.reshape(rand_tensor1,(7,1))
torch.matmul(rand_tensor,reshape_tensor1)

tensor([[1.2838],
        [0.6454],
        [1.8734],
        [0.7676],
        [1.6895],
        [1.4852],
        [1.0361]])

In [19]:
import torch
rand_tensor1=torch.rand(1,7)
torch.matmul(rand_tensor,rand_tensor1.T)

tensor([[1.3982],
        [1.4957],
        [2.4668],
        [0.9379],
        [1.9409],
        [1.3697],
        [1.6070]])

##Set the random seed to 0 and do exercises 2 & 3 over again.


In [22]:
import torch
RANDOM_SEED=0
torch.manual_seed(seed=RANDOM_SEED)
rand_tensor=torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
rand_tensor1=torch.rand(1,7)
torch.matmul(rand_tensor,rand_tensor1.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

##Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [23]:
import torch
torch.cuda.manual_seed(1234)


##Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).


In [4]:
import torch
torch.manual_seed(1234)
rand_1=torch.rand(2,3)
torch.manual_seed(1234)
rand_2=torch.rand(2,3)
if torch.cuda.is_available():
  rand_1=rand_1.to("cuda")
  rand_2=rand_2.to("cuda")

print(rand_1)
print(rand_2)
torch.cuda.is_available()


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')


True

##Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors)

In [9]:
matrix_mul=torch.matmul(rand_1,rand_2.T)
matrix_mul

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

##Find the maximum and minimum values of the output of 7.

In [12]:
matrix_mul.max(),matrix_mul.min()

(tensor(0.6287, device='cuda:0'), tensor(0.2161, device='cuda:0'))

##Find the maximum and minimum index values of the output of 7.

In [13]:
torch.argmax(matrix_mul),torch.argmin(matrix_mul)

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))

##Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.


In [21]:
torch.manual_seed(7)
rand_tensor=torch.rand(1,1,1,10)
one_dim=torch.squeeze(rand_tensor)
print(f"first_tensor:{rand_tensor}")
print(f"first_tensor_shape:{rand_tensor.shape}")
print(f"second_tensor:{one_dim}")
print(f"second_tensor_shape:{one_dim.shape}")

first_tensor:tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
first_tensor_shape:torch.Size([1, 1, 1, 10])
second_tensor:tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
second_tensor_shape:torch.Size([10])
